language: python
python:
  - "3.5"
services: mysql

env:
  - DJANGO=2.0.3
install:
  - pip install -r requirements.txt
before_script:
  - mysql -e 'create database travis_ci_db;'
  - python manage.py migrate
script:
  - python manage.py test
